name: Retrieve Branch Name

on:
  push:
    branches:
      - '*'

permissions:
  contents: write  # Grant write permission to GITHUB_TOKEN

jobs:
  retrieve-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Branch Name
        echo "Current Branch: $GITHUB_REF" > README.md

      - name: Write Branch Name to README.md
        echo "Current Branch: $GITHUB_REF" > README.md

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with current branch name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
