name: Retrieve Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  retrieve-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Branch Name
        run: echo "Current Branch: ${{ github.ref }}"
